// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using challenge_back.Models;

#nullable disable

namespace challengeback.Migrations
{
    [DbContext(typeof(ChallengeContext))]
    [Migration("20230310183036_add_Persona")]
    partial class addPersona
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("challenge_back.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Sexo")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Silva",
                            Documento = "42901989",
                            Edad = 22,
                            Nombre = "Luca",
                            Sexo = (byte)0
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Watson",
                            Documento = "4564546",
                            Edad = 27,
                            Nombre = "Emma",
                            Sexo = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Silva",
                            Documento = "42901989",
                            Edad = 19,
                            Nombre = "Ciro",
                            Sexo = (byte)0
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Anastacia",
                            Documento = "4564233",
                            Edad = 18,
                            Nombre = "Micaela",
                            Sexo = (byte)1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
